name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: DOCKER_BUILDKIT=1 docker build -o type=tar,dest=nano.tar .

      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: nano.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nano.tar
          path: nano.tar
